spring:
  datasource:
    url: jdbc:postgresql://shop-db:5432/nfo-shop
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  kafka:
    producer:
      #    FIXME change to docker image port
      bootstrap-servers: kafka-store:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

nfo-client:
  ribbon:
    listOfServers: nfo-client:8081