version: '3.8'

services:
#  Shop App
  nfo-shop:
    image: 'nfo-shop:latest'
    build: ./nfo-shop
    container_name: nfo-shop
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://shop-db:5432/nfo-shop
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
    ports:
      - 8080:8080
    depends_on:
      - shop-db
    links:
      - shop-db
  shop-db:
    image: 'postgres:13.1-alpine'
    container_name: shop-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=nfo-shop
    restart: unless-stopped
# Auth app
  nfo-client:
    image: 'nfo-client:latest'
    build: ./nfo-client
    container_name: nfo-client
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://client-db:5432/nfo-client
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
    depends_on:
      - client-db
    links:
      - client-db
  client-db:
    image: 'postgres:13.1-alpine'
    container_name: client-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=nfo-client
    restart: unless-stopped