version: '3.8'

services:
  #  Shop app db
  shop-db:
    image: 'postgres:13.1-alpine'
    container_name: shop-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=nfo-shop
    restart: unless-stopped
  # Auth app db
  client-db:
    image: 'postgres:13.1-alpine'
    container_name: client-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=nfo-client
    restart: unless-stopped