spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nfo-client
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yaml

server:
  port : 8081